stages:
  - Build

Build Docker Container:
  stage: Build
  tags: [ shell ]
  script:
    - docker buildx bake --file docker-bake.hcl php-minicrawler --progress=plain #--push
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always