stages:
  - Build

Build Docker Container:
  stage: Build
  tags: [ shell ]
  script:
    - docker info
    - docker context ls | grep -q builder || docker context create builder
  #    - docker context create builder
  #    - docker buildx create --name builder --use
  #  script:
  #    - docker buildx bake --file docker-bake.hcl php-minicrawler --print
  after_script:
    - docker buildx du
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always