stages:
  - Build

Build Docker Container:
  stage: Build
  tags: [ shell ]

  before_script: >
    if ! docker context inspect builder > /dev/null 2>&1; then
      docker context create builder
    fi
    
    if ! docker buildx inspect builder > /dev/null 2>&1; then
      docker buildx create --name builder --use
    fi

  script: >
    docker buildx bake --file docker-bake.hcl php-minicrawler --print

  after_script: >
    docker buildx prune
    docker buildx du

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always