stages:
  - Build

Build Docker Container:
  stage: Build
  tags: [ shell ]
  script:
    - time docker context create builder
    - time docker buildx create --name builder --use
    - time docker buildx bake --file docker-bake.hcl php-minicrawler --print
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always