Cleanup docker cache:
  tags: [ shell ]
  script:
    - docker buildx prune --force
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true

Build php-minicrawler container:
  tags: [ shell ]

  before_script: >
    if ! docker context inspect builder > /dev/null 2>&1; then
      docker context create builder
    fi
    
    if ! docker buildx inspect builder > /dev/null 2>&1; then
      docker buildx create --name builder --use
    fi

  script:
    - docker buildx bake --file docker-bake.hcl php-minicrawler --print
    - docker buildx bake --file docker-bake.hcl php-minicrawler --push

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "*.c"
        - "*.h"
        - "*.xml"
        - "*.php"
        - ".docker/Dockerfile"
      when: always
    - when: manual
