name: php-minicrawler

services:

  # docker compose build php-minicrawler-dev
  # docker compose run --rm php-minicrawler-dev /bin/bash
  php-minicrawler-dev:
    tty: true
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: php-minicrawler-dev
    volumes:
      - ".:/php-minicrawler"